#!/bin/sh

FOREVER_PATH=`which forever`

test -z "$NODE_ENV" &&
  export NODE_ENV='development'

if [ "$NODE_ENV" = "development" ]; then
  $FOREVER_PATH -f startup/forever/development.json
else
  $FOREVER_PATH start startup/forever/production.json
fi
