#!/bin/sh

forever=`which forever`

test -z "$NODE_ENV" &&
  export NODE_ENV='development'

if [ "$NODE_ENV" = "development" ]; then
  $forever -f startup/forever/development.json
else
  $forever start startup/forever/production.json
fi
