name: Node-CI Beta

on:
  push:
    branches: [beta-*.*.*, beta]
  workflow_dispatch:

jobs:
  build_and_test:
    uses: homebridge/.github/.github/workflows/nodejs-build-and-test.yml@main
    with:
      enable_coverage: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    needs: build_and_test
    uses: homebridge/.github/.github/workflows/eslint.yml@main

  publish:
    needs: lint

    if: ${{ secrests.npm_token != null }}

    uses: homebridge/.github/.github/workflows/npm-publish.yml@main
    with:
      tag: 'beta'
      dynamically_adjust_version: true
      npm_version_command: 'pre'
      pre_id: 'beta'
    secrets:
      npm_auth_token: ${{ secrets.npm_token }}
