name: Release Drafter

on:
  push:
    branches: [latest]
  pull_request: # required for autolabeler
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  release-drafter:
    uses: homebridge/.github/.github/workflows/release-drafter.yml@latest
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
